-- Drop tables if they exist
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

-- Create customer table with unique constraint on username
CREATE TABLE customer
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password  VARCHAR(255) NOT NULL,
    username  VARCHAR(255) NOT NULL UNIQUE,
    user_role ENUM ('ADMIN','CUSTOMER'),
    PRIMARY KEY (id)
);

-- Create assets table
CREATE TABLE assets
(
    size        NUMERIC(38, 2) NOT NULL,
    usable_size NUMERIC(38, 2) NOT NULL,
    customer_id BIGINT         NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_name  VARCHAR(255)   NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK4e3uppjyg1krutc0i0lp50asy FOREIGN KEY (customer_id) REFERENCES customer
);

-- Create orders table
CREATE TABLE orders
(
    price       NUMERIC(38, 2),
    size        INTEGER NOT NULL,
    create_date TIMESTAMP(6),
    customer_id BIGINT,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_name  VARCHAR(255),
    order_side  ENUM ('BUY','SELL'),
    status      ENUM ('CANCELED','MATCHED','PENDING'),
    PRIMARY KEY (id),
    CONSTRAINT FK624gtjin3po807j3vix093tlf FOREIGN KEY (customer_id) REFERENCES customer
);
